// Code generated by protoc-gen-go. DO NOT EDIT.
// source: textanalytics.proto

package textanalytics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BatchDetectLanguageRequest struct {
	Documents            []*BatchDetectLanguageRequest_Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *BatchDetectLanguageRequest) Reset()         { *m = BatchDetectLanguageRequest{} }
func (m *BatchDetectLanguageRequest) String() string { return proto.CompactTextString(m) }
func (*BatchDetectLanguageRequest) ProtoMessage()    {}
func (*BatchDetectLanguageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95bbfc17710757c6, []int{0}
}

func (m *BatchDetectLanguageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDetectLanguageRequest.Unmarshal(m, b)
}
func (m *BatchDetectLanguageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDetectLanguageRequest.Marshal(b, m, deterministic)
}
func (m *BatchDetectLanguageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDetectLanguageRequest.Merge(m, src)
}
func (m *BatchDetectLanguageRequest) XXX_Size() int {
	return xxx_messageInfo_BatchDetectLanguageRequest.Size(m)
}
func (m *BatchDetectLanguageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDetectLanguageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDetectLanguageRequest proto.InternalMessageInfo

func (m *BatchDetectLanguageRequest) GetDocuments() []*BatchDetectLanguageRequest_Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type BatchDetectLanguageRequest_Document struct {
	// Unique, non-empty document identifier.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchDetectLanguageRequest_Document) Reset()         { *m = BatchDetectLanguageRequest_Document{} }
func (m *BatchDetectLanguageRequest_Document) String() string { return proto.CompactTextString(m) }
func (*BatchDetectLanguageRequest_Document) ProtoMessage()    {}
func (*BatchDetectLanguageRequest_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_95bbfc17710757c6, []int{0, 0}
}

func (m *BatchDetectLanguageRequest_Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDetectLanguageRequest_Document.Unmarshal(m, b)
}
func (m *BatchDetectLanguageRequest_Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDetectLanguageRequest_Document.Marshal(b, m, deterministic)
}
func (m *BatchDetectLanguageRequest_Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDetectLanguageRequest_Document.Merge(m, src)
}
func (m *BatchDetectLanguageRequest_Document) XXX_Size() int {
	return xxx_messageInfo_BatchDetectLanguageRequest_Document.Size(m)
}
func (m *BatchDetectLanguageRequest_Document) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDetectLanguageRequest_Document.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDetectLanguageRequest_Document proto.InternalMessageInfo

func (m *BatchDetectLanguageRequest_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BatchDetectLanguageRequest_Document) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type DetectedLanguage struct {
	// "Long name of a detected language (e.g. English, French).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A two letter representation of the detected language according to
	// the ISO 639-1 standard (e.g. en, fr).
	Iso6391Name string `protobuf:"bytes,2,opt,name=iso6391name,json=iso6391Name,proto3" json:"iso6391name,omitempty"`
	// A confidence score between 0 and 1.
	// Scores close to 1 indicate 100% certainty that the identified language is true.
	Score                float64  `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectedLanguage) Reset()         { *m = DetectedLanguage{} }
func (m *DetectedLanguage) String() string { return proto.CompactTextString(m) }
func (*DetectedLanguage) ProtoMessage()    {}
func (*DetectedLanguage) Descriptor() ([]byte, []int) {
	return fileDescriptor_95bbfc17710757c6, []int{1}
}

func (m *DetectedLanguage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectedLanguage.Unmarshal(m, b)
}
func (m *DetectedLanguage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectedLanguage.Marshal(b, m, deterministic)
}
func (m *DetectedLanguage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectedLanguage.Merge(m, src)
}
func (m *DetectedLanguage) XXX_Size() int {
	return xxx_messageInfo_DetectedLanguage.Size(m)
}
func (m *DetectedLanguage) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectedLanguage.DiscardUnknown(m)
}

var xxx_messageInfo_DetectedLanguage proto.InternalMessageInfo

func (m *DetectedLanguage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetectedLanguage) GetIso6391Name() string {
	if m != nil {
		return m.Iso6391Name
	}
	return ""
}

func (m *DetectedLanguage) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type BatchDetectLanguageResponse struct {
	Documents            []*BatchDetectLanguageResponse_Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *BatchDetectLanguageResponse) Reset()         { *m = BatchDetectLanguageResponse{} }
func (m *BatchDetectLanguageResponse) String() string { return proto.CompactTextString(m) }
func (*BatchDetectLanguageResponse) ProtoMessage()    {}
func (*BatchDetectLanguageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95bbfc17710757c6, []int{2}
}

func (m *BatchDetectLanguageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDetectLanguageResponse.Unmarshal(m, b)
}
func (m *BatchDetectLanguageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDetectLanguageResponse.Marshal(b, m, deterministic)
}
func (m *BatchDetectLanguageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDetectLanguageResponse.Merge(m, src)
}
func (m *BatchDetectLanguageResponse) XXX_Size() int {
	return xxx_messageInfo_BatchDetectLanguageResponse.Size(m)
}
func (m *BatchDetectLanguageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDetectLanguageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDetectLanguageResponse proto.InternalMessageInfo

func (m *BatchDetectLanguageResponse) GetDocuments() []*BatchDetectLanguageResponse_Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type BatchDetectLanguageResponse_Document struct {
	// Unique document identifier.
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DetectLanguages      []*DetectedLanguage `protobuf:"bytes,2,rep,name=detect_languages,json=detectedLanguages,proto3" json:"detect_languages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BatchDetectLanguageResponse_Document) Reset()         { *m = BatchDetectLanguageResponse_Document{} }
func (m *BatchDetectLanguageResponse_Document) String() string { return proto.CompactTextString(m) }
func (*BatchDetectLanguageResponse_Document) ProtoMessage()    {}
func (*BatchDetectLanguageResponse_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_95bbfc17710757c6, []int{2, 0}
}

func (m *BatchDetectLanguageResponse_Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDetectLanguageResponse_Document.Unmarshal(m, b)
}
func (m *BatchDetectLanguageResponse_Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDetectLanguageResponse_Document.Marshal(b, m, deterministic)
}
func (m *BatchDetectLanguageResponse_Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDetectLanguageResponse_Document.Merge(m, src)
}
func (m *BatchDetectLanguageResponse_Document) XXX_Size() int {
	return xxx_messageInfo_BatchDetectLanguageResponse_Document.Size(m)
}
func (m *BatchDetectLanguageResponse_Document) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDetectLanguageResponse_Document.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDetectLanguageResponse_Document proto.InternalMessageInfo

func (m *BatchDetectLanguageResponse_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BatchDetectLanguageResponse_Document) GetDetectLanguages() []*DetectedLanguage {
	if m != nil {
		return m.DetectLanguages
	}
	return nil
}

type BatchKeyPhrasesRequest struct {
	Documents            []*BatchKeyPhrasesRequest_Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *BatchKeyPhrasesRequest) Reset()         { *m = BatchKeyPhrasesRequest{} }
func (m *BatchKeyPhrasesRequest) String() string { return proto.CompactTextString(m) }
func (*BatchKeyPhrasesRequest) ProtoMessage()    {}
func (*BatchKeyPhrasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_95bbfc17710757c6, []int{3}
}

func (m *BatchKeyPhrasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchKeyPhrasesRequest.Unmarshal(m, b)
}
func (m *BatchKeyPhrasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchKeyPhrasesRequest.Marshal(b, m, deterministic)
}
func (m *BatchKeyPhrasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchKeyPhrasesRequest.Merge(m, src)
}
func (m *BatchKeyPhrasesRequest) XXX_Size() int {
	return xxx_messageInfo_BatchKeyPhrasesRequest.Size(m)
}
func (m *BatchKeyPhrasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchKeyPhrasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchKeyPhrasesRequest proto.InternalMessageInfo

func (m *BatchKeyPhrasesRequest) GetDocuments() []*BatchKeyPhrasesRequest_Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type BatchKeyPhrasesRequest_Document struct {
	// This is the 2 letter ISO 639-1 representation of a language.
	// For example, use "en" for English; "es" for Spanish etc.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Unique, non-empty document identifier.
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchKeyPhrasesRequest_Document) Reset()         { *m = BatchKeyPhrasesRequest_Document{} }
func (m *BatchKeyPhrasesRequest_Document) String() string { return proto.CompactTextString(m) }
func (*BatchKeyPhrasesRequest_Document) ProtoMessage()    {}
func (*BatchKeyPhrasesRequest_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_95bbfc17710757c6, []int{3, 0}
}

func (m *BatchKeyPhrasesRequest_Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchKeyPhrasesRequest_Document.Unmarshal(m, b)
}
func (m *BatchKeyPhrasesRequest_Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchKeyPhrasesRequest_Document.Marshal(b, m, deterministic)
}
func (m *BatchKeyPhrasesRequest_Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchKeyPhrasesRequest_Document.Merge(m, src)
}
func (m *BatchKeyPhrasesRequest_Document) XXX_Size() int {
	return xxx_messageInfo_BatchKeyPhrasesRequest_Document.Size(m)
}
func (m *BatchKeyPhrasesRequest_Document) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchKeyPhrasesRequest_Document.DiscardUnknown(m)
}

var xxx_messageInfo_BatchKeyPhrasesRequest_Document proto.InternalMessageInfo

func (m *BatchKeyPhrasesRequest_Document) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *BatchKeyPhrasesRequest_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BatchKeyPhrasesRequest_Document) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type BatchKeyPhrasesResponse struct {
	Documents            []*BatchKeyPhrasesResponse_Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *BatchKeyPhrasesResponse) Reset()         { *m = BatchKeyPhrasesResponse{} }
func (m *BatchKeyPhrasesResponse) String() string { return proto.CompactTextString(m) }
func (*BatchKeyPhrasesResponse) ProtoMessage()    {}
func (*BatchKeyPhrasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_95bbfc17710757c6, []int{4}
}

func (m *BatchKeyPhrasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchKeyPhrasesResponse.Unmarshal(m, b)
}
func (m *BatchKeyPhrasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchKeyPhrasesResponse.Marshal(b, m, deterministic)
}
func (m *BatchKeyPhrasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchKeyPhrasesResponse.Merge(m, src)
}
func (m *BatchKeyPhrasesResponse) XXX_Size() int {
	return xxx_messageInfo_BatchKeyPhrasesResponse.Size(m)
}
func (m *BatchKeyPhrasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchKeyPhrasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchKeyPhrasesResponse proto.InternalMessageInfo

func (m *BatchKeyPhrasesResponse) GetDocuments() []*BatchKeyPhrasesResponse_Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type BatchKeyPhrasesResponse_Document struct {
	// Unique document identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A list of representative words or phrases.
	// The number of key phrases returned is proportional to
	// the number of words in the input document.
	KeyPhrases           []string `protobuf:"bytes,2,rep,name=key_phrases,json=keyPhrases,proto3" json:"key_phrases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchKeyPhrasesResponse_Document) Reset()         { *m = BatchKeyPhrasesResponse_Document{} }
func (m *BatchKeyPhrasesResponse_Document) String() string { return proto.CompactTextString(m) }
func (*BatchKeyPhrasesResponse_Document) ProtoMessage()    {}
func (*BatchKeyPhrasesResponse_Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_95bbfc17710757c6, []int{4, 0}
}

func (m *BatchKeyPhrasesResponse_Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchKeyPhrasesResponse_Document.Unmarshal(m, b)
}
func (m *BatchKeyPhrasesResponse_Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchKeyPhrasesResponse_Document.Marshal(b, m, deterministic)
}
func (m *BatchKeyPhrasesResponse_Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchKeyPhrasesResponse_Document.Merge(m, src)
}
func (m *BatchKeyPhrasesResponse_Document) XXX_Size() int {
	return xxx_messageInfo_BatchKeyPhrasesResponse_Document.Size(m)
}
func (m *BatchKeyPhrasesResponse_Document) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchKeyPhrasesResponse_Document.DiscardUnknown(m)
}

var xxx_messageInfo_BatchKeyPhrasesResponse_Document proto.InternalMessageInfo

func (m *BatchKeyPhrasesResponse_Document) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BatchKeyPhrasesResponse_Document) GetKeyPhrases() []string {
	if m != nil {
		return m.KeyPhrases
	}
	return nil
}

func init() {
	proto.RegisterType((*BatchDetectLanguageRequest)(nil), "textanalytics.BatchDetectLanguageRequest")
	proto.RegisterType((*BatchDetectLanguageRequest_Document)(nil), "textanalytics.BatchDetectLanguageRequest.Document")
	proto.RegisterType((*DetectedLanguage)(nil), "textanalytics.DetectedLanguage")
	proto.RegisterType((*BatchDetectLanguageResponse)(nil), "textanalytics.BatchDetectLanguageResponse")
	proto.RegisterType((*BatchDetectLanguageResponse_Document)(nil), "textanalytics.BatchDetectLanguageResponse.Document")
	proto.RegisterType((*BatchKeyPhrasesRequest)(nil), "textanalytics.BatchKeyPhrasesRequest")
	proto.RegisterType((*BatchKeyPhrasesRequest_Document)(nil), "textanalytics.BatchKeyPhrasesRequest.Document")
	proto.RegisterType((*BatchKeyPhrasesResponse)(nil), "textanalytics.BatchKeyPhrasesResponse")
	proto.RegisterType((*BatchKeyPhrasesResponse_Document)(nil), "textanalytics.BatchKeyPhrasesResponse.Document")
}

func init() { proto.RegisterFile("textanalytics.proto", fileDescriptor_95bbfc17710757c6) }

var fileDescriptor_95bbfc17710757c6 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xd1, 0x4e, 0xfa, 0x30,
	0x14, 0xc6, 0xd3, 0xf1, 0xff, 0x1b, 0x38, 0x44, 0x83, 0xd5, 0xe8, 0x82, 0x17, 0x2c, 0xbb, 0xe2,
	0x6a, 0x46, 0x48, 0x4c, 0x8c, 0x77, 0x86, 0x2b, 0x45, 0x83, 0x7d, 0x00, 0x49, 0x5d, 0x4f, 0x60,
	0x01, 0x56, 0xa4, 0x25, 0x91, 0x97, 0xf1, 0xce, 0x17, 0xf0, 0x71, 0x7c, 0x1a, 0x43, 0xd7, 0x21,
	0xd0, 0x89, 0xde, 0xb5, 0x67, 0x3d, 0xbf, 0x73, 0xbe, 0xef, 0xcb, 0xe0, 0x48, 0xe3, 0xab, 0xe6,
	0x29, 0x1f, 0x2f, 0x74, 0x12, 0xab, 0x68, 0x3a, 0x93, 0x5a, 0xd2, 0xfd, 0x8d, 0x62, 0xf8, 0x46,
	0xa0, 0x7e, 0xc3, 0x75, 0x3c, 0xec, 0xa0, 0xc6, 0x58, 0x77, 0x79, 0x3a, 0x98, 0xf3, 0x01, 0x32,
	0x7c, 0x99, 0xa3, 0xd2, 0xb4, 0x07, 0x15, 0x21, 0xe3, 0xf9, 0x04, 0x53, 0xad, 0x7c, 0x12, 0x94,
	0x9a, 0xd5, 0x56, 0x2b, 0xda, 0xc4, 0xfe, 0xdc, 0x1d, 0x75, 0x6c, 0x2b, 0xfb, 0x86, 0xd4, 0x23,
	0x28, 0xe7, 0x65, 0x7a, 0x00, 0x5e, 0x22, 0x7c, 0x12, 0x90, 0x66, 0x85, 0x79, 0x89, 0xa0, 0x14,
	0xfe, 0x2d, 0xd9, 0xbe, 0x67, 0x2a, 0xe6, 0x1c, 0x3e, 0x41, 0x2d, 0x83, 0xa3, 0xc8, 0xf1, 0xcb,
	0x77, 0x29, 0x9f, 0xa0, 0xed, 0x34, 0x67, 0x1a, 0x40, 0x35, 0x51, 0xf2, 0xb2, 0x7d, 0x75, 0x61,
	0x3e, 0x65, 0x88, 0xbc, 0xf4, 0xb0, 0x7c, 0x71, 0x0c, 0xff, 0x55, 0x2c, 0x67, 0xe8, 0x97, 0x02,
	0xd2, 0x24, 0x2c, 0xbb, 0x84, 0x9f, 0x04, 0xce, 0x0a, 0x25, 0xa8, 0xa9, 0x4c, 0x15, 0xd2, 0x47,
	0xd7, 0x81, 0xf6, 0x5f, 0x1c, 0xc8, 0xda, 0x0b, 0x2d, 0x18, 0xee, 0xb0, 0xa0, 0x0b, 0x35, 0x61,
	0x48, 0xfd, 0xb1, 0x45, 0x29, 0xdf, 0x33, 0x53, 0x1b, 0x5b, 0x53, 0xb7, 0x5d, 0x61, 0x87, 0x62,
	0xab, 0xa2, 0xc2, 0x0f, 0x02, 0x27, 0x66, 0xbb, 0x3b, 0x5c, 0xf4, 0x86, 0x33, 0xae, 0x50, 0xe5,
	0xc9, 0x76, 0x5d, 0x5d, 0x51, 0x91, 0x2e, 0xa7, 0xb3, 0x50, 0xd2, 0xed, 0x9a, 0xa4, 0x3a, 0x94,
	0xf3, 0xdd, 0xad, 0xb0, 0xd5, 0xdd, 0xca, 0xf5, 0x9c, 0xc4, 0x4b, 0x6b, 0x89, 0xbf, 0x13, 0x38,
	0x75, 0x46, 0xdb, 0x34, 0xee, 0xdd, 0xad, 0xcf, 0x7f, 0xdb, 0x7a, 0x47, 0x12, 0xd7, 0x3b, 0x92,
	0x68, 0x40, 0x75, 0x84, 0x8b, 0xfe, 0x34, 0xc3, 0x98, 0x10, 0x2a, 0x0c, 0x46, 0x2b, 0xf0, 0xf3,
	0x9e, 0xf9, 0xa1, 0xda, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0x59, 0xac, 0x38, 0x67, 0x03,
	0x00, 0x00,
}
